<?php

/**
 * 快递公司编码与名称
 *
 * @author yuxinqi<yuxinqi@vip.qq.com>
 * @version 1.0
 * @link http://docs.liangjianyun.com?/
 */


if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}

return array(
    'AJ' =>  lang("plugin/aljhtx","express_company_php_1"),
    'ANE' =>  lang("plugin/aljhtx","express_company_php_2"),
    'AXD' =>  lang("plugin/aljhtx","express_company_php_3"),
    'BQXHM' =>  lang("plugin/aljhtx","express_company_php_4"),
    'BFDF' =>  lang("plugin/aljhtx","express_company_php_5"),
    'BTWL' =>  lang("plugin/aljhtx","express_company_php_6"),
    'CCES' =>  'CCES',
    'CITY100' =>  lang("plugin/aljhtx","express_company_php_7").'100',
    'COE' =>  lang("plugin/aljhtx","express_company_php_8"),
    'CSCY' =>  lang("plugin/aljhtx","express_company_php_9"),
    'CDSTKY' =>  lang("plugin/aljhtx","express_company_php_10"),
    'DBL' =>  lang("plugin/aljhtx","express_company_php_11"),
    'DSWL' =>  'D'.lang("plugin/aljhtx","express_company_php_12"),
    'DTWL' =>  lang("plugin/aljhtx","express_company_php_13"),
    'EMS' =>  'EMS',
    'FAST' =>  lang("plugin/aljhtx","express_company_php_14"),
    'FEDEX' =>  lang("plugin/aljhtx","express_company_php_15"),
    'FEDEX_GJ' =>  lang("plugin/aljhtx","express_company_php_16"),
    'FKD' =>  lang("plugin/aljhtx","express_company_php_17"),
    'GDEMS' =>  lang("plugin/aljhtx","express_company_php_18"),
    'GSD' =>  lang("plugin/aljhtx","express_company_php_19"),
    'GTO' =>  lang("plugin/aljhtx","express_company_php_20"),
    'GTSD' =>  lang("plugin/aljhtx","express_company_php_21"),
    'HFWL' =>  lang("plugin/aljhtx","express_company_php_22"),
    'HHTT' =>  lang("plugin/aljhtx","express_company_php_23"),
    'HLWL' =>  lang("plugin/aljhtx","express_company_php_24"),
    'HOAU' =>  lang("plugin/aljhtx","express_company_php_25"),
    'hq568' =>  lang("plugin/aljhtx","express_company_php_26"),
    'HTKY' =>  lang("plugin/aljhtx","express_company_php_27"),
    'HXLWL' =>  lang("plugin/aljhtx","express_company_php_28"),
    'HYLSD' =>  lang("plugin/aljhtx","express_company_php_29"),
    'JGSD' =>  lang("plugin/aljhtx","express_company_php_30"),
    'JIUYE' =>  lang("plugin/aljhtx","express_company_php_31"),
    'JJKY' =>  lang("plugin/aljhtx","express_company_php_32"),
    'JLDT' =>  lang("plugin/aljhtx","express_company_php_33"),
    'JTKD' =>  lang("plugin/aljhtx","express_company_php_34"),
    'JXD' =>  lang("plugin/aljhtx","express_company_php_35"),
    'JYKD' =>  lang("plugin/aljhtx","express_company_php_36"),
    'JYM' =>  lang("plugin/aljhtx","express_company_php_37"),
    'JYWL' =>  lang("plugin/aljhtx","express_company_php_38"),
    'KYWL' =>  lang("plugin/aljhtx","express_company_php_39"),
    'LB' =>  lang("plugin/aljhtx","express_company_php_40"),
    'LHT' =>  lang("plugin/aljhtx","express_company_php_41"),
    'MHKD' =>  lang("plugin/aljhtx","express_company_php_42"),
    'MLWL' =>  lang("plugin/aljhtx","express_company_php_43"),
    'NEDA' =>  lang("plugin/aljhtx","express_company_php_44"),
    'PADTF' =>  lang("plugin/aljhtx","express_company_php_45"),
    'QCKD' =>  lang("plugin/aljhtx","express_company_php_46"),
    'QFKD' =>  lang("plugin/aljhtx","express_company_php_47"),
    'QRT' =>  lang("plugin/aljhtx","express_company_php_48"),
    'RFD' =>  lang("plugin/aljhtx","express_company_php_49"),
    'SAD' =>  lang("plugin/aljhtx","express_company_php_50"),
    'SAWL' =>  lang("plugin/aljhtx","express_company_php_51"),
    'SBWL' =>  lang("plugin/aljhtx","express_company_php_52"),
    'SDWL' =>  lang("plugin/aljhtx","express_company_php_53"),
    'SF' =>  lang("plugin/aljhtx","express_company_php_54"),
    'SFWL' =>  lang("plugin/aljhtx","express_company_php_55"),
    'SHWL' =>  lang("plugin/aljhtx","express_company_php_56"),
    'ST' =>  lang("plugin/aljhtx","express_company_php_57"),
    'STO' =>  lang("plugin/aljhtx","express_company_php_58"),
    'STWL' =>  lang("plugin/aljhtx","express_company_php_59"),
    'SURE' =>  lang("plugin/aljhtx","express_company_php_60"),
    'TSSTO' =>  lang("plugin/aljhtx","express_company_php_61"),
    'UAPEX' =>  lang("plugin/aljhtx","express_company_php_62"),
    'UC' =>  lang("plugin/aljhtx","express_company_php_63"),
    'WJWL' =>  lang("plugin/aljhtx","express_company_php_64"),
    'WXWL' =>  lang("plugin/aljhtx","express_company_php_65"),
    'XBWL' =>  lang("plugin/aljhtx","express_company_php_66"),
    'XFEX' =>  lang("plugin/aljhtx","express_company_php_67"),
    'XYT' =>  lang("plugin/aljhtx","express_company_php_68"),
    'XJ' =>  lang("plugin/aljhtx","express_company_php_69"),
    'YADEX' =>  lang("plugin/aljhtx","express_company_php_70"),
    'YCWL' =>  lang("plugin/aljhtx","express_company_php_71"),
    'YD' =>  lang("plugin/aljhtx","express_company_php_72"),
    'YDH' =>  lang("plugin/aljhtx","express_company_php_73"),
    'YFEX' =>  lang("plugin/aljhtx","express_company_php_74"),
    'YFHEX' =>  lang("plugin/aljhtx","express_company_php_75"),
    'YFSD' =>  lang("plugin/aljhtx","express_company_php_76"),
    'YTKD' =>  lang("plugin/aljhtx","express_company_php_77"),
    'YTO' =>  lang("plugin/aljhtx","express_company_php_78"),
    'YXKD' =>  lang("plugin/aljhtx","express_company_php_79"),
    'YZPY' =>  lang("plugin/aljhtx","express_company_php_80"),
    'ZENY' =>  lang("plugin/aljhtx","express_company_php_81"),
    'ZHQKD' =>  lang("plugin/aljhtx","express_company_php_82"),
    'ZJS' =>  lang("plugin/aljhtx","express_company_php_83"),
    'ZTE' =>  lang("plugin/aljhtx","express_company_php_84"),
    'ZTKY' =>  lang("plugin/aljhtx","express_company_php_85"),
    'ZTO' =>  lang("plugin/aljhtx","express_company_php_86"),
    'ZTWL' =>  lang("plugin/aljhtx","express_company_php_87"),
    'ZYWL' =>  lang("plugin/aljhtx","express_company_php_88"),
    'AMAZON' =>  lang("plugin/aljhtx","express_company_php_89"),
    'SUBIDA' =>  lang("plugin/aljhtx","express_company_php_90"),
    'RFEX' =>  lang("plugin/aljhtx","express_company_php_91"),
    'QUICK' =>  lang("plugin/aljhtx","express_company_php_92"),
    'CJKD' =>  lang("plugin/aljhtx","express_company_php_93"),
    'CNPEX' =>  lang("plugin/aljhtx","express_company_php_94"),
    'HOTSCM' =>  lang("plugin/aljhtx","express_company_php_95"),
    'HPTEX' =>  lang("plugin/aljhtx","express_company_php_96"),
    'AYCA' =>  lang("plugin/aljhtx","express_company_php_97"),
    'PANEX' =>  lang("plugin/aljhtx","express_company_php_98"),
    'PCA' =>  'PCA Express',
    'UEQ' =>  'UEQ Express',
);